## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):    
    obj = bld.create_ns3_program('MultiCoreSim', ['core'])
    obj.source = [
  'tinyxml.cpp',
  'tinyxmlerror.cpp',
  'tinyxmlparser.cpp',
  'tinystr.cpp',
  'MCoreSimProject.cc',
  'CpuCoreGenerator.cc',
  'PrivateCacheCtrl.cc',
  'SharedCacheCtrl.cc',
  'DRAMCtrl.cc',
  'BusArbiter.cc',
  'LatencyLogger.cc',
  'IdGenerator.cc',
	]



